[gcloud]
disabled = true

[kubernetes]
# symbol = 'Ó†ù '
disabled = false
format = '[$symbol $context( \($namespace\))]($style) in '

[[kubernetes.contexts]]
# "green" style + a different symbol when Kubernetes current context name contains openshift
context_pattern = "(?P<ns>[\\w-]+)-service@o1"
context_alias = "$ns@o1"

[[kubernetes.contexts]]
# Using capture groups
# Contexts from GKE, AWS and other cloud providers usually carry additional information, like the region/zone.
# The following entry matches on the GKE format (`gke_projectname_zone_cluster-name`)
# and renames every matching kube context into a more readable format (`gke-cluster-name`):
context_pattern = "gke_.*_(?P<cluster>[\\w-]+)"
context_alias = "gke-$cluster"

